top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/mappers
builddir     = /home/jiamin/httpd-2.4.23/modules/mappers
VPATH        = /home/jiamin/httpd-2.4.23/modules/mappers

include $(top_srcdir)/build/special.mk

