top_srcdir   = /home/jiamin/httpd
top_builddir = /home/jiamin/httpd
srcdir       = /home/jiamin/httpd/modules/mappers
builddir     = /home/jiamin/httpd/modules/mappers
VPATH        = /home/jiamin/httpd/modules/mappers

include $(top_srcdir)/build/special.mk

