top_srcdir   = /home/jiamin/httpd
top_builddir = /home/jiamin/httpd
srcdir       = /home/jiamin/httpd/modules/metadata
builddir     = /home/jiamin/httpd/modules/metadata
VPATH        = /home/jiamin/httpd/modules/metadata

include $(top_srcdir)/build/special.mk

