top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/metadata
builddir     = /home/jiamin/httpd-2.4.23/modules/metadata
VPATH        = /home/jiamin/httpd-2.4.23/modules/metadata

include $(top_srcdir)/build/special.mk

