top_srcdir   = /home/jiamin/httpd
top_builddir = /home/jiamin/httpd
srcdir       = /home/jiamin/httpd/modules/proxy/balancers
builddir     = /home/jiamin/httpd/modules/proxy/balancers
VPATH        = /home/jiamin/httpd/modules/proxy/balancers
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
