top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/generators
builddir     = /home/jiamin/httpd-2.4.23/modules/generators
VPATH        = /home/jiamin/httpd-2.4.23/modules/generators

include $(top_srcdir)/build/special.mk

