top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/database
builddir     = /home/jiamin/httpd-2.4.23/modules/database
VPATH        = /home/jiamin/httpd-2.4.23/modules/database
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
