top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/aaa
builddir     = /home/jiamin/httpd-2.4.23/modules/aaa
VPATH        = /home/jiamin/httpd-2.4.23/modules/aaa

include $(top_srcdir)/build/special.mk

