top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/server/mpm/event
builddir     = /home/jiamin/httpd-2.4.23/server/mpm/event
VPATH        = /home/jiamin/httpd-2.4.23/server/mpm/event
include $(top_srcdir)/build/special.mk
