top_srcdir   = /home/jiamin/httpd
top_builddir = /home/jiamin/httpd
srcdir       = /home/jiamin/httpd/server/mpm/event
builddir     = /home/jiamin/httpd/server/mpm/event
VPATH        = /home/jiamin/httpd/server/mpm/event
include $(top_srcdir)/build/special.mk
