top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/cache
builddir     = /home/jiamin/httpd-2.4.23/modules/cache
VPATH        = /home/jiamin/httpd-2.4.23/modules/cache

include $(top_srcdir)/build/special.mk

