top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/os
builddir     = /home/jiamin/httpd-2.4.23/os
VPATH        = /home/jiamin/httpd-2.4.23/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
