top_srcdir   = /home/jiamin/httpd
top_builddir = /home/jiamin/httpd
srcdir       = /home/jiamin/httpd/modules/core
builddir     = /home/jiamin/httpd/modules/core
VPATH        = /home/jiamin/httpd/modules/core

include $(top_srcdir)/build/special.mk

