top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/core
builddir     = /home/jiamin/httpd-2.4.23/modules/core
VPATH        = /home/jiamin/httpd-2.4.23/modules/core

include $(top_srcdir)/build/special.mk

