top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/modules/http
builddir     = /home/jiamin/httpd-2.4.23/modules/http
VPATH        = /home/jiamin/httpd-2.4.23/modules/http

include $(top_srcdir)/build/special.mk

