top_srcdir   = /home/jiamin/httpd-2.4.23
top_builddir = /home/jiamin/httpd-2.4.23
srcdir       = /home/jiamin/httpd-2.4.23/server/mpm
builddir     = /home/jiamin/httpd-2.4.23/server/mpm
VPATH        = /home/jiamin/httpd-2.4.23/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
